const User = require('../models/user.model');
const UserPlans = require('../models/User_plans');
const Plans = require('../models/Plans');
const MiningSubscription = require('../models/MiningSubscription');
const MiningPlan = require('../models/MiningPlan');
const CopyPosition = require('../models/CopyPosition');
const Expert = require('../models/Expert');
const BotSubscription = require('../models/BotSubscription');
const TradingBot = require('../models/TradingBot');
const { notifyUser } = require('./notification.service');

const n = v => Number.isFinite(Number(v)) ? Number(v) : 0;
const stepMs = v => { const s=String(v||'Daily').toLowerCase(); if(s.includes('10 minute'))return 600000;if(s.includes('30 minute'))return 1800000;if(s.includes('hour'))return 3600000;if(s.includes('week'))return 604800000;if(s.includes('month'))return 2592000000;return 86400000; };
const planDurationMs = p => { const m=String(p.expiration||'').match(/(\d+(?:\.\d+)?)\s*(year|month|week|day|hour|minute)/i); if(!m)return n(p.duration||30)*86400000; const u=m[2].toLowerCase(), mult={year:31536000000,month:2592000000,week:604800000,day:86400000,hour:3600000,minute:60000}; return n(m[1])*mult[u]; };
const planRate = p => n(p.increment_amount??p.return??p.max_return??p.maxr);
async function tickInvestments(){
 const rows=await UserPlans.find({active:'yes'}).populate('plan');
 for(const r of rows){const p=r.plan;if(!p)continue;const now=Date.now(),last=new Date(r.last_growth||r.activated_at||r.createdAt).getTime(),end=Math.min(now,new Date(r.expire_date).getTime()),step=stepMs(p.increment_interval||p.t_interval),ticks=Math.floor((end-last)/step);if(ticks>0){const per=String(p.increment_type||p.t_type||'Percentage').toLowerCase().includes('fixed')?planRate(p):n(r.amount)*planRate(p)/100;const total=Math.max(0,per*ticks);const cap=Math.max(0,Math.floor(planDurationMs(p)/step)*per);r.profit_earned=Math.min(cap,n(r.profit_earned)+total);r.payments_received=n(r.payments_received)+ticks;r.last_growth=new Date(last+ticks*step);await r.save();}}
 const expired=await UserPlans.find({active:'yes',expire_date:{$lte:new Date()}}).populate('plan');
 for(const r of expired){const p=r.plan;if(!p)continue;const ok=await UserPlans.findOneAndUpdate({_id:r._id,active:'yes'},{$set:{active:'expired',closed_at:new Date(),settled_at:new Date(),settlement_type:'expired'}},{new:true});if(!ok)continue;const u=await User.findById(r.user);if(!u)continue;u.account_bal=n(u.account_bal)+n(r.amount)+n(r.profit_earned);await u.save();await notifyUser(u,'investment','Plan balance added',`Your investment plan balances on(${p.name}) are added to your account.`,'/user/notification.html',{icon:'bell'});}
}
async function tickMining(){const rows=await MiningSubscription.find({status:'active'}).populate('mining_plan_id').populate('user_id');for(const r of rows){const p=r.mining_plan_id;if(!p)continue;const now=Date.now(),last=new Date(r.last_growth||r.started_at||r.createdAt).getTime(),end=Math.min(now,new Date(r.expires_at).getTime()),ticks=Math.floor((end-last)/86400000);if(ticks>0){r.accumulated_profit=n(r.accumulated_profit)+n(r.invested_amount)*n(r.daily_roi_snapshot)/100*ticks;r.last_growth=new Date(last+ticks*86400000);await r.save();}if(new Date(r.expires_at)<=new Date()){const fresh=await MiningSubscription.findOne({_id:r._id,status:'active'}).populate('user_id').populate('mining_plan_id');if(!fresh)continue;const payout=n(fresh.invested_amount)+n(fresh.accumulated_profit)+n(fresh.admin_profit_adjustment);fresh.status='completed';fresh.settled_at=new Date();await fresh.save();fresh.user_id.account_bal+=payout;await fresh.user_id.save();await notifyUser(fresh.user_id,'trade','Mining Settled',`Your mining subscription has been settled. $${payout.toFixed(2)} has been credited to your balance.`,'/user/notification.html',{icon:'bell'});}}}
async function tickCopy(){const rows=await CopyPosition.find({status:'active'}).populate('expert').populate('user_id');for(const r of rows){const now=Date.now(),last=new Date(r.last_growth||r.started_at||r.createdAt).getTime(),end=Math.min(now,new Date(r.expires_at).getTime()),ticks=Math.floor((end-last)/86400000);if(ticks>0){r.accumulated_profit=n(r.accumulated_profit)+n(r.invested_amount)*n(r.daily_roi_snapshot)/100*ticks;r.last_growth=new Date(last+ticks*86400000);await r.save();}if(new Date(r.expires_at)<=new Date()){const fresh=await CopyPosition.findOne({_id:r._id,status:'active'}).populate('user_id').populate('expert');if(!fresh)continue;const payout=n(fresh.invested_amount)+n(fresh.accumulated_profit)+n(fresh.admin_profit_adjustment);fresh.status='completed';fresh.settled_at=new Date();await fresh.save();fresh.user_id.account_bal+=payout;await fresh.user_id.save();await notifyUser(fresh.user_id,'copy_trade','coptrade stopped',`Your copytrade was completed and $${payout.toFixed(2)} has been credited to your balance.`,'/user/notification.html',{icon:'bell'});}}}
async function tickBots(){const rows=await BotSubscription.find({status:'active'}).populate('bot_id').populate('user_id');for(const r of rows){const step=Math.max(60000,n(r.bot_id?.trade_interval_minutes)*60000||86400000),now=Date.now(),last=new Date(r.last_growth||r.started_at||r.createdAt).getTime(),end=Math.min(now,new Date(r.expires_at).getTime()),ticks=Math.floor((end-last)/step);if(ticks>0){r.current_profit=n(r.current_profit)+n(r.invested_amount)*n(r.daily_roi_snapshot)/100*(step/86400000)*ticks;r.last_growth=new Date(last+ticks*step);await r.save();}if(new Date(r.expires_at)<=new Date()){const fresh=await BotSubscription.findOne({_id:r._id,status:'active'}).populate('user_id').populate('bot_id');if(!fresh)continue;const payout=n(fresh.invested_amount)+n(fresh.current_profit)+n(fresh.admin_profit_adjustment);fresh.status='completed';fresh.settled_at=new Date();await fresh.save();fresh.user_id.account_bal+=payout;await fresh.user_id.save();await notifyUser(fresh.user_id,'trade','Bot Subscription Settled',`Your bot subscription has been settled. $${payout.toFixed(2)} has been credited to your balance.`,'/user/notification.html',{icon:'bell'});}}}
function startFeatureLifecycle(){
 setInterval(()=>Promise.allSettled([tickInvestments(),tickMining(),tickCopy(),tickBots()]).catch(()=>{}),60000);
}

module.exports={startFeatureLifecycle,tickInvestments,tickMining,tickCopy,tickBots};
